spring:
  cloud:
    stream:
      bindings:
        output:
          destination: logs-topic
          content-type: application/json
          producer:
            required-groups: log-group
      kafka:
        binder:
          brokers: kafka:9093
          auto-create-topics: false
          default-topic: logs-topic
